### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by gigafunk** [sbtoonz/DegradeFoodOnMove#1]
Hey I had to rebuild the dll with the new game files top get it to work. I have a working dll now, i just finished so ill fully test it on my server tomorrow. I bumped the version, referenced the newest serversync dll, and updated it to .net 4.8.1,  but no changes otherwise. 

Im not sure the dot net was required but i had trouble with the dot net environment setup on my end. 

also i am not sure the serversync dll was needed but i was having alot of trouble building it reference wise.

Its just a little problematic with the mod launcher to give it to my server friends. If you get a chance , could you update the thunderstore? 

ill test it on my server tomorrow, but it booted fine in the single player game

**Comment by sbtoonz** [comment]
[sbtoonz-Food_Degrade_Only_On_Move-1.0.0.zip](https://github.com/user-attachments/files/15540132/sbtoonz-Food_Degrade_Only_On_Move-1.0.0.zip)
here is a fixed zip

**Comment by gigafunk** [comment]
thanks man
